#pragma config(Sensor, in1,    light,          sensorAnalog)
#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move() {
	//motor[left] = vexRT[Ch3];


	if (vexRT[Btn6U] == 1) {
		motor[left] = 96;
		motor[right] = 96;
	} else if (vexRT[Btn5U] == 1) {
		motor[left] = -96;
		motor[right] = -96;
	} else if (vexRT[Btn6D] == 1) {
		motor[left] = 96;
		motor[right] = -96;
	} else if (vexRT[Btn5D] == 1) {
		motor[left] = -96;
		motor[right] = 96;
	} else {
		motor[left] = 0;
		motor[right] = 0;
	}

	/*
	motor[left] = vexRT[Ch3];
	motor[right] = vexRT[Ch3];

	int turn = vexRT[Ch1];
	if (turn < 0) {
		motor[left] += turn;
		motor[right] -= turn;
	} else if (turn > 0) {
		motor[left] -= turn;
		motor[right] += turn;
	}
	*/
}

task main() {
	while (true) {
		move();

		/*
		if (SensorValue(light) <= 150) { //about 130 ambient
			motor[left] = 127;
		} else {
			motor[left] = 0;
		}
		*/
	}
}
